### ISSUE TITLE
Feat: Pod scheduling control

### ISSUE THREAD

**Issue by leoendless** [kubesphere/console#1413]
**What would you like to be added**:

Design a suitable way to make pod scheduling control more convenient and flexible.

Functions to be implemented:

1. Support to edit affinity and anti-affinity through UI.
2. Support to edit pod's node selector through UI.

**Why is this needed**:

Refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node

In many cases, pods need to be scheduled to specific nodes, or scheduled with pods of certain services, or prevent from being scheduled to specific nodes, etc.

Currently, ks-console only partially supports affinity, allowing centralized or decentralized scheduling of workload pods.
![image](https://user-images.githubusercontent.com/8739949/103772996-5ac96880-5065-11eb-97a2-914e89cd5003.png)

And edit the node selector in the [Advanced Settings]. But after the workload is created, the node selector can no longer be modified through the UI.
![image](https://user-images.githubusercontent.com/8739949/103773181-9fed9a80-5065-11eb-8ca4-ec2204ffcf27.png)

**Comment by leoendless** [comment]
It will be very convenient if we can display the node list of the current cluster for users to choose from. But there seems to be some permission problems. @wansir

**Comment by leoendless** [comment]
It seems that pod affinity/anti-affinity can be simplified to be deployed with or away from the pod of a certain workload.

**Comment by wansir** [comment]
/assign  

I think the permissions of list node can be granted by default.

**Comment by leoendless** [comment]
> /assign
> 
> I think the permissions of list node can be granted by default.

Do we need to restrict some special nodes from being selected?

**Comment by wansir** [comment]
> > /assign
> > I think the permissions of list node can be granted by default.
> 
> Do some special nodes need to be restricted from being selected?
> 
> Or the cluster-admin can tag some nodes with special labels, and the normal users can only choose from these nodes.

We can use [Gatekeepter](https://github.com/open-policy-agent/gatekeeper), which will be a new feature.

**Comment by cw514102209** [comment]
> **What would you like to be added**:
> 
> Design a suitable way to make pod scheduling control more convenient and flexible.
> 
> Functions to be implemented:
> 
> 1. Support to edit affinity and anti-affinity through UI.
> 2. Support to edit pod's node selector through UI.
> 
> **Why is this needed**:
> 
> Refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node
> 
> In many cases, pods need to be scheduled to specific nodes, or scheduled with pods of certain services, or prevent from being scheduled to specific nodes, etc.
> 
> Currently, ks-console only partially supports affinity, allowing centralized or decentralized scheduling of workload pods.
> ![image](https://user-images.githubusercontent.com/8739949/103772996-5ac96880-5065-11eb-97a2-914e89cd5003.png)
> 
> And edit the node selector in the [Advanced Settings]. But after the workload is created, the node selector can no longer be modified through the UI.
> ![image](https://user-images.githubusercontent.com/8739949/103773181-9fed9a80-5065-11eb-8ca4-ec2204ffcf27.png)

I would like to contribute to resolving this issue.

**Comment by cw514102209** [comment]
I would like to contribute to resolving this issue.

**Comment by cw514102209** [comment]
> It seems that pod affinity/anti-affinity can be simplified to be deployed with or away from the pod of a certain workload.
> So we could let the user choose a workload, and choose a policy(with or away from).
> 
> The user needs to specify these three values on the UI:
> 
> ```
> workload: workloadName
> policy: affinity | antiAffinity
> type: required | preffer
> ```
> 
> Then, ks-console will transfer these values to k8s `spec.affinity`.
> 
> ```yaml
>     spec:
>       affinity:
>         podAntiAffinity:
>           preferredDuringSchedulingIgnoredDuringExecution:
>           - labelSelector:
>               matchExpressions:
>               - key: app
>                 operator: In
>                 values:
>                 - web-store
>             topologyKey: "kubernetes.io/hostname"
>         podAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>           - labelSelector:
>               matchExpressions:
>               - key: app
>                 operator: In
>                 values:
>                 - store
>             topologyKey: "kubernetes.io/hostname"
> ```

## About pod affinity and anti-affinity

We have designed some UI that we can discuss together.

![affinity](https://user-images.githubusercontent.com/44636460/104416154-424dd680-55ae-11eb-9851-919e2a99a3f9.png)

If the user fills in affinity and selects the appropriate scheduling method. Then, ks-console will transfer these values to k8s spec.affinity.

```
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - val1
        topologyKey: kubernetes.io/hostname
```

```
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - val2
          topologyKey: kubernetes.io/hostname
```

```
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - val1
        topologyKey: kubernetes.io/hostname
```

```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - val2
          topologyKey: kubernetes.io/hostname
```

**Comment by cw514102209** [comment]
## About pod affinity and anti-affinity

We have designed some UI that we can discuss together.

![affinity](https://user-images.githubusercontent.com/44636460/104416416-bb4d2e00-55ae-11eb-9b7b-e0b196197acd.png)

If the user fills in affinity and selects the appropriate scheduling method. Then, ks-console will transfer these values to k8s spec.affinity.

```
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - val1
        topologyKey: kubernetes.io/hostname
```

```
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - val2
          topologyKey: kubernetes.io/hostname
```

```
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - val1
        topologyKey: kubernetes.io/hostname
```

```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - val2
          topologyKey: kubernetes.io/hostname
```
