### ISSUE TITLE
Not found error appears when querying CR on the CRD page

### ISSUE THREAD

**Issue by liabio** [kubesphere/console#1723]
**Describe the bug**

Not found error appears when querying CR on the CRD page
![query cr not found error](https://user-images.githubusercontent.com/21979752/112976926-088d7480-9188-11eb-966d-c2aba7cde505.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0
Kubernetes: v1.18.14

**Environment**
3 masters, also as nodes:  88cpu/1T

**To Reproduce**
1. Save this yaml content to file kibana-crd.yaml, then kubectl apply -f kibana-crd.yaml：
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: kibanas.kibana.k8s.elastic.co
spec:
  additionalPrinterColumns:
  - JSONPath: .status.health
    name: health
    type: string
  - JSONPath: .status.availableNodes
    description: Available nodes
    name: nodes
    type: integer
  - JSONPath: .status.version
    description: Kibana version
    name: version
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: date
  group: kibana.k8s.elastic.co
  names:
    categories:
    - elastic
    kind: Kibana
    listKind: KibanaList
    plural: kibanas
    shortNames:
    - kb
    singular: kibana
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1beta1
    served: true
    storage: false
  - name: v1alpha1
    served: false
    storage: false
```

2. http://localhost:8000/clusters/host/customresources/kibanas.kibana.k8s.elastic.co/resources
![image](https://user-images.githubusercontent.com/21979752/112977598-d3355680-9188-11eb-81c1-45fbf8bd5b9a.png)
3. click Kibana to query kibana CR

**Expected behavior**

Query  three kibana CR is expected， like kubectl query result：
```shell
# kubectl get kibanas.kibana.k8s.elastic.co  -A
NAMESPACE   NAME        HEALTH   NODES   VERSION   AGE
arch-xadd   kb-pubsub   green    1       7.10.0    81d
arch-xadd   kb-xadd-a   green    1       7.10.0    133d
cdc         kb-cdc-a    green    1       7.10.1    11d
```

**Comment by liabio** [comment]
In fact, for this issue, I have located the reason, as follows:

my kibana CR refer：
https://github.com/elastic/cloud-on-k8s/blob/master/config/crds/all-crds.yaml#L3490

![CRD versions](https://user-images.githubusercontent.com/21979752/112978370-d9780280-9189-11eb-9bb2-0ad9cc5f5b05.png)

kibana CRD versions likes this：
```yaml
spec:
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1beta1
    served: true
    storage: false
  - name: v1alpha1
    served: false
    storage: false
```

served：Served is a flag enabling/disabling this version from being served via REST APIs

so ， false indicates that  v1alpha1 will not be registered in the k8s APIServer.

But kubesphere/console/src/utils/object.mapper.js：
![console source bug position](https://user-images.githubusercontent.com/21979752/112978655-32479b00-918a-11eb-8b6b-6b346fdc17b8.png)

The last index name v1alpha1 was fetched, so a 404 error occurred.

I open this issue and try to fix it.
