### ISSUE TITLE
Mount config or secret selection specific key path input error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2430]
**Describe the bug**
1. Mount the config, select a specific key, and enter the path "/data1"
2. click save,click to confirm,pod does not update
3. Change the path to "data1",click save,click to confirm 
4. pod updated successfully

https://user-images.githubusercontent.com/88183150/136767018-74f1980b-10f8-41d5-b87e-d82d0c164219.mp4

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks-console:nightly-20211010

/kind bug
/@kubesphere/sig-console
/priority medium

**Comment by weili520** [comment]
@kubesphere/sig-multicluster, please take a look at this problem. The rohan cluster doesn't update when I change the config map mount path, but other clusters are updated.

https://user-images.githubusercontent.com/33231138/145745037-5a270b5c-c970-4a3a-a0a4-7cd6520e1b09.mov

**Comment by iawia002** [comment]
This is caused by resource quota restrictions, the rohan cluster has set a resource quota, and the remaining is not enough to create another Pod, so the new Pod cannot be created, it looks like it has not been updated.

```yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-13T02:38:18Z"
    lastUpdateTime: "2021-12-13T02:38:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-13T02:51:31Z"
    lastUpdateTime: "2021-12-13T02:51:31Z"
    message: 'admission webhook "resourcesquotas.quota.kubesphere.io" denied the request:
      pods "hello-75d84bc58-8tqcd" is forbidden: exceeded quota: dsdadadas, requested:
      limits.cpu=500m, used: limits.cpu=500m, limited: limits.cpu=800m'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

Just increase the quota below and everything will be OK.

<img width="2231" alt="Screen Shot 2021-12-13 at 11 15 01 AM" src="https://user-images.githubusercontent.com/9134003/145746877-9cac95e6-5674-4c96-b26f-7cf354d28cf8.png">
