### ISSUE TITLE
Incorrect status display of DevOps Projects

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#2591]
**Describe the bug**

Incorrect status display of DevOps Projects. Please see the screenshot:

![image](https://user-images.githubusercontent.com/16865714/140958949-85010db5-e9ef-4a7d-99d1-5c3dffe7ad3b.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0
Kubernetes: v1.21.5

**To Reproduce**
1. Stop Deployment `devops-jenkins`
2. Create a DevOps Project
3. See DevOps Projects

**Expected behavior**

When the DevOps Project is pending to synchronize, the status should be `Pending` instead of `Active`.

/area devops
/kind bug
/priority high

**Comment by JohnNiang** [comment]
Exactly, we should improve the `status` part of CRD `DevOpsProject`. Just like below:

```yaml
apiVersion: devops.kubesphere.io/v1alpha3
kind: DevOpsProject
metadata:
  name: project-name
spec:
staus:
  phase: Pending # Current project phase. Pending, Success or Failed
```

---

But I suggest using this temporary solution now: using annotation `devopsproject.devops.kubesphere.io/syncstatus` to display the DevOps Project status in the table.
