### ISSUE TITLE
Add label to Fluent Bit Operator Input/Filter/Output to distinguish data flow

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#294]
To distinguish data flow for logging, events and auditing, please add the label to all **Input/Filter/Output** custom resources like below:

Add label `logging.kubesphere.io/component`

```
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: es
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  match: kube.*
  es:
    host: elasticsearch-logging-data.kubesphere-logging-system.svc
    port: 9200
    logstashPrefix: ks-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"
```

Frontend should only show Outputs that have the label `logging.kubesphere.io/component: logging`:

`/apis/logging.kubesphere.io/v1alpha2/namespaces/kubesphere-logging-system/outputs?labelSelector=logging.kubesphere.io/component=logging`

![image](https://user-images.githubusercontent.com/22350668/83092838-c2cbcf80-a0d0-11ea-8c99-3e5ddfacdad3.png)
