### ISSUE TITLE
Can't enter deployment detail page

### ISSUE THREAD

**Issue by weili520** [kubesphere/console#3074]
**General remarks**

**Describe the bug**

User can't enter deatil page, it will be blank, and get error as follows:

![截屏2022-04-12 11 41 37](https://user-images.githubusercontent.com/33231138/162875830-2a428cdd-184d-453e-bf2c-293247661329.png)

It caused by this deployment's pods has two network ip setting, but one of them doesn't has `ips` key:
 
![截屏2022-04-12 11 48 11](https://user-images.githubusercontent.com/33231138/162876533-d57f5aaa-fdaf-4e09-bdb5-03c5004ba4e8.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3-alpha.0

**Environment**

All in one cluster:  4cpu/4g

**To Reproduce**

+ This deployment config yaml:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vpc-nat-gw-nat-gateway
  namespace: kube-system
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpc-nat-gw-nat-gateway
      ovn.kubernetes.io/vpc-nat-gw: 'true'
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vpc-nat-gw-nat-gateway
        ovn.kubernetes.io/vpc-nat-gw: 'true'
      annotations:
        k8s.v1.cni.cncf.io/networks: kube-system/ovn-vpc-external-network
        ovn.kubernetes.io/ip_address: 10.0.1.254
        ovn.kubernetes.io/logical_switch: net1
        ovn.kubernetes.io/vpc_nat_gw: nat-gateway
    spec:
      containers:
        - name: vpc-nat-gw
          image: 'kubeovn/vpc-nat-gateway:v1.9.0'
          command:
            - bash
          args:
            - '-c'
            - while true; do sleep 10000; done
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: node1
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

**Expected behavior**
 
User can enter detail page.
