### ISSUE TITLE
Add Language Support for Korean

### ISSUE THREAD

**Issue by jihoon-seo** [kubesphere/console#4269]
**What would you like to be added**:
Add Language Support for Korean.

**Why is this needed**:
It will make Kubesphere more accessible to Korean users.

I installed Kubesphere v3.4.0 on my minikube cluster, and saw that Korean does not exist in language options of Kubesphere (console).
![image](https://github.com/kubesphere/console/assets/46767780/3c08bbc8-bb57-4a62-9c3e-7156bfda69b2)
![image](https://github.com/kubesphere/console/assets/46767780/58fd30eb-4bf1-4615-a279-798422be94f6)

And in Kubesphere Crowdin project, it is displayed that words and strings are 99% translated into Korean.

So it would be great if we can add language support for Korean, by doing some necessary work, where one of them might be to include localized L10n `.js` files that exist in the Crowdin project.

If someone can guide or at least provide some hints, then I might be able to work on this.

**Comment by calvinyv** [comment]
thanks for your help, we're on a three-day public holiday, and our front-end developers will be providing documentation after the holiday.

**Comment by donniean** [comment]
You need to add the Korean entry to `supportLangs` in [`server/config.yaml`](https://github.com/kubesphere/console/blob/master/server/config.yaml#L60)

For example

```yaml
client
    supportLangs:
    - label: 'English'
      value: 'en'
      recommend: true
    # other languages ...
    - label: 'Korean in the Korean language'
      value: 'ko'
```
